variable "application_type" {}
variable "resource_type" {}
variable "resource_group" {}
variable "location" {}
variable "subnet_id" {}
variable "public_ip_address_id" {}
variable "vm_username" {}
variable "vm_password" {}
variable "image_name" {}
variable "image_resource_group_name" {}
